from contextlib import asynccontextmanager

from fastapi import Depends, FastAPI, HTTPException
from sqlalchemy import select, text
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

from . import models, schemas
from .database import Base, engine, get_db


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Run startup and shutdown logic for the FastAPI application.
    """

    # Create all database tables that do not already exist.
    Base.metadata.create_all(bind=engine)

    yield


app = FastAPI(
    title="Ticket Analyzer API",
    description="Backend API for the Ticket Analyzer project.",
    version="0.3.0",
    lifespan=lifespan,
)


@app.get("/")
def read_root() -> dict[str, str]:
    return {"message": "Ticket Analyzer API is running"}


@app.get("/health")
def health_check() -> dict[str, str]:
    """
    Confirm that both FastAPI and PostgreSQL are available.
    """

    try:
        with engine.connect() as connection:
            connection.execute(text("SELECT 1"))

    except SQLAlchemyError as error:
        raise HTTPException(
            status_code=503,
            detail="Database is unavailable",
        ) from error

    return {"status": "ok"}


@app.post(
    "/tickets",
    response_model=schemas.TicketResponse,
    status_code=201,
)
def create_ticket(
    ticket_data: schemas.TicketCreate,
    db: Session = Depends(get_db),
):
    """
    Create and save a new support ticket.
    """

    new_ticket = models.Ticket(
        title=ticket_data.title,
        message=ticket_data.message,
        category=ticket_data.category,

        # Temporary values.
        # These will be replaced by the AI model later.
        sentiment="PENDING",
        confidence=0.0,
    )

    try:
        # Prepare the ticket to be inserted.
        db.add(new_ticket)

        # Save the ticket permanently in PostgreSQL.
        db.commit()

        # Reload the ticket to obtain values generated by PostgreSQL,
        # such as id and created_at.
        db.refresh(new_ticket)

    except SQLAlchemyError as error:
        # Cancel unfinished database changes if something fails.
        db.rollback()

        raise HTTPException(
            status_code=500,
            detail="Could not save the ticket",
        ) from error

    return new_ticket


@app.get(
    "/tickets",
    response_model=list[schemas.TicketResponse],
)
def get_tickets(
    db: Session = Depends(get_db),
):
    """
    Return all saved tickets, newest first.
    """

    try:
        statement = select(models.Ticket).order_by(
            models.Ticket.created_at.desc()
        )

        tickets = db.scalars(statement).all()

    except SQLAlchemyError as error:
        raise HTTPException(
            status_code=500,
            detail="Could not retrieve tickets",
        ) from error

    return tickets